"""Tests for the ``--inject`` backend.

The end-to-end path needs a real game, but most of what can go wrong is testable
here: the generated script must be valid Python at the right indentation with its
configuration embedded, the manifest reader must classify every record honestly, the
write-probe must refuse a read-only directory with a message that points at
``--runtime``, and cleanup must remove the compiled ``.rpyc`` as well as the ``.rpy``.

The ``.rpyc`` detail is the one that bites in practice: leaving it behind makes the
game re-run the extraction on every launch.
"""

from __future__ import annotations

import json
import unittest
from pathlib import Path

from test_support import ScratchCase

from renpy_unpack.inject import (
    InjectError,
    InjectResult,
    Injector,
    build_script,
)
from renpy_unpack.runtime import RuntimeLayout


def make_layout(root: Path, *, with_launcher: bool = True) -> RuntimeLayout:
    python = root / "lib" / "py3-windows-x86_64" / "python.exe"
    python.parent.mkdir(parents=True, exist_ok=True)
    python.write_bytes(b"")
    (root / "renpy").mkdir(parents=True, exist_ok=True)
    (root / "game").mkdir(parents=True, exist_ok=True)
    launcher = None
    if with_launcher:
        launcher = root / "SomeGame.py"
        launcher.write_text(
            "def path_to_gamedir(basedir, name):\n    return basedir\n",
            encoding="utf-8",
        )
    return RuntimeLayout(
        python=python, game_root=root, renpy_dir=root / "renpy", launcher=launcher
    )


class TestBuildScript(unittest.TestCase):
    CONFIG = {
        "output": "/tmp/out",
        "manifest": "/tmp/m.jsonl",
        "only": [".rpy"],
        "skip_existing": False,
    }

    @staticmethod
    def body_of(source: str) -> str:
        """Extract the indented body and dedent it back to plain Python.

        The generated file is a *Ren'Py script*, so ``compile()`` cannot be applied
        to it directly -- ``init python early:`` is not Python syntax.  The body
        inside the block is, and that is what has to be valid.
        """
        lines = source.splitlines()[2:]  # drop the comment and the `init` line
        out = []
        for line in lines:
            out.append(line[4:] if line.startswith("    ") else line)
        return "\n".join(out)

    def test_generated_body_is_valid_python(self):
        body = self.body_of(build_script(self.CONFIG))
        compile(body, "<generated body>", "exec")

    def test_every_body_line_is_indented_inside_the_block(self):
        """The body is written at column 0 in the template and indented by us.

        A stray unindented line would end the ``init python early:`` block early and
        turn extraction code into top-level game script.
        """
        source = build_script(self.CONFIG)
        lines = source.splitlines()
        self.assertEqual(
            lines[0], "# Generated by renpy_unpack --inject. Safe to delete."
        )
        self.assertEqual(lines[1], "init python early:")
        for number, line in enumerate(lines[2:], start=3):
            if line.strip():
                self.assertTrue(
                    line.startswith("    "),
                    f"line {number} is not indented: {line!r}",
                )

    def test_config_is_embedded_not_referenced(self):
        # One file write, nothing extra to clean up, no chance of drift.
        source = build_script(self.CONFIG)
        self.assertIn(json.dumps(self.CONFIG), source)
        self.assertNotIn("__CONFIG_JSON__", source)

    def test_config_survives_quoting_hazards(self):
        # Windows paths and quotes must not break out of the literal.
        nasty = {
            "output": "C:\\Games\\it's \"quoted\"\\out",
            "manifest": "C:\\tmp\\m.jsonl",
            "only": [".rpy", ".rpyc"],
            "skip_existing": True,
        }
        source = build_script(nasty)
        compile(self.body_of(source), "<generated body>", "exec")

        marker = "_CONFIG = json.loads("
        line = next(l for l in source.splitlines() if marker in l)
        literal = line.strip()[len(marker) : -1]
        self.assertEqual(json.loads(eval(literal)), nasty)  # noqa: S307 - test fixture

    def test_generated_body_defines_what_the_run_needs(self):
        body = self.body_of(build_script(self.CONFIG))
        # Reads the index the loader already built, exits before the game plays.
        self.assertIn("renpy.loader", body)
        self.assertIn("load_from_archive", body)
        self.assertIn("os._exit(0)", body)
        # No window, no game loop.
        self.assertNotIn("renpy.exports", body)


class TestManifestReading(ScratchCase):
    def write(self, records: list[dict]) -> Path:
        path = self.path("manifest.jsonl")
        path.write_text(
            "\n".join(json.dumps(r) for r in records) + "\n", encoding="utf-8"
        )
        return path

    def test_statuses_are_classified(self):
        result = InjectResult()
        result.absorb(
            self.write(
                [
                    {"name": "a", "status": "ok", "size": 10},
                    {"name": "b", "status": "ok", "size": 5},
                    {"name": "c", "status": "skipped", "size": 0},
                    {"name": "d", "status": "missing", "size": 0},
                    {"name": "e", "status": "error", "size": 0, "error": "boom"},
                    {"name": "", "status": "done", "size": 15},
                ]
            )
        )
        self.assertEqual(result.ok, 2)
        self.assertEqual(result.skipped, 1)
        self.assertEqual(result.missing, 1)
        self.assertEqual(result.failed, 1)
        self.assertEqual(result.bytes_written, 15)
        self.assertEqual(len(result.failures), 2)

    def test_partial_manifest_still_reports_what_completed(self):
        """A crash mid-run leaves earlier records; count them rather than nothing."""
        result = InjectResult()
        result.absorb(
            self.write(
                [
                    {"name": "a", "status": "ok", "size": 1},
                    {"name": "", "status": "fatal", "size": 0, "error": "died"},
                ]
            )
        )
        self.assertEqual(result.ok, 1)
        self.assertIn("died", result.fatal)

    def test_malformed_lines_are_skipped(self):
        path = self.path("m.jsonl")
        path.write_text(
            'not json\n{"name":"a","status":"ok","size":3}\n\n', encoding="utf-8"
        )
        result = InjectResult()
        result.absorb(path)
        self.assertEqual(result.ok, 1)

    def test_absent_manifest_is_not_an_error_here(self):
        result = InjectResult()
        result.absorb(self.path("nope.jsonl"))
        self.assertEqual(result.ok, 0)


class TestWriteProbe(ScratchCase):
    def test_read_only_directory_is_refused_with_a_useful_message(self):
        """This is the normal case for an installed game, so the message matters."""
        readonly = self.path("ReadOnly")
        readonly.mkdir()

        real_write_text = Path.write_text

        def deny(self, *args, **kwargs):  # noqa: ANN001
            raise OSError(13, "Permission denied")

        Path.write_text = deny  # type: ignore[method-assign]
        try:
            with self.assertRaises(InjectError) as ctx:
                Injector._check_writable(readonly)
        finally:
            Path.write_text = real_write_text  # type: ignore[method-assign]

        message = str(ctx.exception)
        self.assertIn("cannot write into", message)
        self.assertIn("--runtime", message)

    def test_writable_directory_passes_and_leaves_no_probe_file(self):
        target = self.path("Writable")
        target.mkdir()
        Injector._check_writable(target)
        self.assertEqual(list(target.iterdir()), [])


class TestCleanup(ScratchCase):
    def test_rpy_and_rpyc_are_both_removed(self):
        root = self.path("Game")
        layout = make_layout(root)
        injector = Injector(layout, self.path("out"))
        script = injector.script_path()
        script.write_text("init python early:\n    pass\n", encoding="utf-8")
        compiled = script.with_suffix(".rpyc")
        compiled.write_text("bytecode", encoding="utf-8")

        scratch = self.path("scratch")
        scratch.mkdir()
        leftovers = injector._cleanup(script, scratch)

        self.assertEqual(leftovers, [])
        self.assertFalse(script.exists())
        self.assertFalse(compiled.exists(), "a leftover .rpyc re-runs on every launch")
        self.assertFalse(scratch.exists())

    def test_keep_script_retains_the_source_but_still_drops_the_bytecode(self):
        root = self.path("Game")
        layout = make_layout(root)
        injector = Injector(layout, self.path("out"), keep_script=True)
        script = injector.script_path()
        script.write_text("x\n", encoding="utf-8")
        compiled = script.with_suffix(".rpyc")
        compiled.write_text("bytecode", encoding="utf-8")

        scratch = self.path("scratch")
        scratch.mkdir()
        injector._cleanup(script, scratch)

        self.assertTrue(script.exists())
        self.assertFalse(compiled.exists())


class TestInjectorPlumbing(ScratchCase):
    def test_script_lands_inside_the_game_directory(self):
        root = self.path("Game")
        layout = make_layout(root)
        injector = Injector(layout, self.path("out"))
        self.assertEqual(injector.game_dir(), root / "game")
        self.assertEqual(injector.script_path(), root / "game" / injector.SCRIPT_NAME)

    def test_scratch_is_not_inside_the_output_directory(self):
        # It held the manifest and log; a stray directory in the output would look
        # like extracted content.
        root = self.path("Game")
        layout = make_layout(root)
        out = self.path("out")
        out.mkdir()
        injector = Injector(layout, out)
        scratch = injector._scratch_dir()
        self.assertNotEqual(scratch, out)
        self.assertNotIn(out, scratch.parents)

    def test_missing_launcher_is_reported_with_the_alternative(self):
        root = self.path("Game")
        layout = make_layout(root, with_launcher=False)
        injector = Injector(layout, self.path("out"))
        with self.assertRaises(InjectError) as ctx:
            injector.launcher()
        self.assertIn("--runtime", str(ctx.exception))

    def test_flags_are_mutually_exclusive(self):
        from renpy_unpack.core import UnpackError, Unpacker

        root = self.path("Game")
        make_layout(root)
        with self.assertRaises(UnpackError) as ctx:
            Unpacker(root, inject=True, runtime=True, progress=False)
        self.assertIn("pick one", str(ctx.exception))

    def test_conflicting_flags_do_not_escape_as_a_traceback(self):
        """The constructor rejects the conflict; ``main`` must report it, not crash.

        ``Unpacker(...)`` was constructed outside the ``try`` that catches
        ``UnpackError``, so ``--inject --runtime`` produced a raw traceback and exit
        code 1 -- the right message at the wrong volume.
        """
        from contextlib import redirect_stderr
        from io import StringIO

        from renpy_unpack.core import main

        buffer = StringIO()
        with redirect_stderr(buffer):
            code = main(
                ["--game", str(self.path("no-such-game")), "--inject", "--runtime"]
            )
        self.assertEqual(code, 2)
        self.assertIn("pick one", buffer.getvalue())
        self.assertNotIn("Traceback", buffer.getvalue())

    def test_plan_only_flags_are_refused_before_any_setup(self):
        """``--list``/``--dry-run`` with ``--inject`` is refused as such.

        Checked before discovery, so a directory that is not a game at all still gets
        the real reason instead of whichever setup step happens to fail first (no
        launcher, no archives, no interpreter).
        """
        from contextlib import redirect_stderr
        from io import StringIO

        from renpy_unpack.core import main

        for extra in (["--list"], ["--dry-run"]):
            buffer = StringIO()
            with redirect_stderr(buffer):
                code = main(
                    ["--game", str(self.path("no-such-game")), "--inject", *extra]
                )
            self.assertEqual(code, 2, extra)
            self.assertIn("cannot be combined", buffer.getvalue())
            self.assertIn("--runtime --list", buffer.getvalue())

    def test_plan_only_flags_are_fine_without_inject(self):
        from renpy_unpack.core import _refuse_inject_with_plan

        class Args:
            inject = False
            list_only = True
            dry_run = True

        self.assertIsNone(_refuse_inject_with_plan(Args()))

    def test_discovery_succeeds_without_loader_source(self):
        """--inject must not require loader.py at all.

        The game's runtime already has the loader loaded, source or bytecode, so
        requiring the source would throw away the one thing --inject can do that
        source-level extraction cannot: work on a build that ships only
        ``loader.pyc``.  Discovery used to fail with "could not find this game's own
        renpy/loader.py" before injection was ever reached.
        """
        from renpy_unpack.core import Unpacker

        root = self.path("Game")
        make_layout(root)
        # Archives present, loader source absent -- the compiled-build shape.
        (root / "game" / "archive.rpa").write_bytes(b"RPA-3.0 " + b"\x00" * 64)

        unpacker = Unpacker(root, inject=True, progress=False)
        unpacker.discover()  # must not raise
        self.assertEqual(unpacker.game_root, root.resolve())

    def test_discovery_still_requires_the_loader_for_other_backends(self):
        # The exemption is specific to --inject; the static backend keeps its rule.
        from renpy_unpack.core import UnpackError, Unpacker

        root = self.path("Game")
        make_layout(root)
        (root / "game" / "archive.rpa").write_bytes(b"RPA-3.0 " + b"\x00" * 64)

        unpacker = Unpacker(root, progress=False)
        with self.assertRaises(UnpackError) as ctx:
            unpacker.discover()
        self.assertIn("renpy/loader.py", str(ctx.exception))


if __name__ == "__main__":
    unittest.main(verbosity=2)
