"""The ``--inject`` backend: let the game unpack itself.

Ren'Py auto-loads every ``.rpy`` under ``game/``, and ``init python early:`` runs
after the loader has built its archive index but before the game plays.  So dropping
a generated script there means the extraction is performed *by the game's own
runtime*, reading an index that already exists and calling the game's own
``load_from_archive()``.

That makes this the most capable backend, and the only one that needs nothing from
``loader.py``: it works on stock RPAv3, on archives disguised as ``.dll`` with a
custom magic and reordered index fields, and on builds that ship only ``loader.pyc``
(where source-level extraction has nothing to read).

The cost is honest and worth stating: it requires a writable ``game/`` directory and
a game that can boot.  Reading somebody's archives should not normally mean writing
into their installation, which is why this is strictly opt-in and why ``--runtime``
and the static backend remain the defaults.

No injection *risk* is added by the mechanism itself: the script is written by this
process, atomically, before the game starts -- there is no window in which anything
else could supply one.
"""

from __future__ import annotations

import json
import os
import shutil
import subprocess
from dataclasses import dataclass, field
from pathlib import Path

from .runtime import RuntimeLayout, RuntimeUnavailable, discover_runtime

__all__ = ["InjectError", "InjectResult", "Injector", "build_script"]


class InjectError(RuntimeError):
    """Injection could not be performed, or the game did not run the script."""


@dataclass
class InjectResult:
    """Outcome of one injection run."""

    ok: int = 0
    skipped: int = 0
    failed: int = 0
    missing: int = 0
    bytes_written: int = 0
    failures: list[tuple[str, str]] = field(default_factory=list)
    fatal: str = ""
    log: str = ""
    script: Path | None = None
    leftovers: list[Path] = field(default_factory=list)

    def absorb(self, manifest: Path) -> None:
        """Read the JSON-lines manifest the injected script wrote."""
        if not manifest.is_file():
            return
        for line in manifest.read_text(encoding="utf-8", errors="replace").splitlines():
            line = line.strip()
            if not line:
                continue
            try:
                record = json.loads(line)
            except ValueError:
                continue
            status = record.get("status")
            if status == "ok":
                self.ok += 1
                self.bytes_written += int(record.get("size") or 0)
            elif status == "skipped":
                self.skipped += 1
            elif status == "missing":
                self.missing += 1
                self.failures.append((record.get("name", "?"), "not in any archive index"))
            elif status == "error":
                self.failed += 1
                self.failures.append(
                    (record.get("name", "?"), record.get("error", "unknown error"))
                )
            elif status == "done":
                # The script's own total; prefer it over the summed sizes.
                self.bytes_written = int(record.get("size") or self.bytes_written)
            elif status == "fatal":
                self.fatal = record.get("error", "unknown fatal error")


def build_script(config: dict) -> str:
    """Wrap the inject body in ``init python early:`` with the config embedded.

    The configuration travels inside the generated file as a JSON literal rather
    than in a side-car file: one write, nothing extra to clean up, and no chance of
    the two getting out of step.
    """
    from pathlib import Path as _Path

    body = _Path(__file__).with_name("_inject_body.py").read_text(encoding="utf-8")
    body = body.replace("__CONFIG_JSON__", repr(json.dumps(config)))

    indented = "\n".join(
        ("    " + line) if line.strip() else "" for line in body.splitlines()
    )
    return (
        "# Generated by renpy_unpack --inject. Safe to delete.\n"
        "init python early:\n" + indented + "\n"
    )


class Injector:
    """Generates the script, runs the game once, collects and cleans up."""

    #: Name used inside ``game/``.  Prefixed so it is obvious it is not the game's.
    SCRIPT_NAME = "zz_renpy_unpack_inject.rpy"

    def __init__(
        self,
        layout: RuntimeLayout,
        output: Path,
        *,
        scratch: Path | None = None,
        only: list[str] | None = None,
        skip_existing: bool = False,
        keep_script: bool = False,
        timeout: float = 3600.0,
    ):
        self.layout = layout
        self.output = Path(output)
        self.scratch = Path(scratch) if scratch else None
        self.only = list(only or [])
        self.skip_existing = skip_existing
        self.keep_script = keep_script
        self.timeout = timeout

    # -- paths -------------------------------------------------------------

    def game_dir(self) -> Path:
        candidate = self.layout.game_root / "game"
        return candidate if candidate.is_dir() else self.layout.game_root

    def script_path(self) -> Path:
        return self.game_dir() / self.SCRIPT_NAME

    def _scratch_dir(self) -> Path:
        """Where the manifest and log live.  Outside ``game/``, never the output."""
        if self.scratch is not None:
            self.scratch.mkdir(parents=True, exist_ok=True)
            return self.scratch
        base = self.output.parent if self.output.parent.is_dir() else self.output
        path = base / f".{self.output.name}.renpy-unpack-inject"
        path.mkdir(parents=True, exist_ok=True)
        return path

    def launcher(self) -> Path:
        if self.layout.launcher is None:
            raise InjectError(
                "this game has no launcher .py to start, so the script cannot be "
                "run automatically. Use --runtime instead."
            )
        return self.layout.launcher

    # -- run ---------------------------------------------------------------

    def run(self) -> InjectResult:
        result = InjectResult()
        script = self.script_path()
        scratch = self._scratch_dir()
        manifest = scratch / "manifest.jsonl"
        log = scratch / "inject.log"

        self._check_writable(self.game_dir())

        self.output.mkdir(parents=True, exist_ok=True)
        manifest.unlink(missing_ok=True)
        log.unlink(missing_ok=True)

        config = {
            "output": str(self.output),
            "manifest": str(manifest),
            "only": self.only,
            "skip_existing": self.skip_existing,
        }

        result.script = script
        try:
            # Written before the game starts, so nothing else can race us here.
            script.write_text(build_script(config), encoding="utf-8")
            self._launch()
            result.absorb(manifest)
            if log.is_file():
                result.log = log.read_text(encoding="utf-8", errors="replace")

            if result.fatal:
                raise InjectError(
                    "the injected script failed inside the game:\n" + result.fatal
                )
            if not manifest.is_file():
                raise InjectError(
                    "the game started but never ran the injected script, so no "
                    "manifest was written. It may have failed before loading "
                    "scripts (a broken game/mod), or the script may have been "
                    "deleted before it ran.\n"
                    + self._log_tail(result.log)
                )
            return result
        finally:
            result.leftovers = self._cleanup(script, scratch)

    def _launch(self) -> None:
        command = [
            str(self.layout.python),
            str(self.launcher()),
        ]
        env = dict(os.environ)
        env.setdefault("RENPY_DISABLE_LOG", "1")
        try:
            subprocess.run(
                command,
                stdout=subprocess.PIPE,
                stderr=subprocess.PIPE,
                timeout=self.timeout,
                cwd=str(self.layout.game_root),
                env=env,
                creationflags=getattr(subprocess, "CREATE_NO_WINDOW", 0),
            )
        except subprocess.TimeoutExpired as exc:
            raise InjectError(
                f"the game did not finish within {self.timeout:.0f}s; the injected "
                "script may not have reached os._exit()."
            ) from exc
        except OSError as exc:
            raise InjectError(
                f"could not start the game's interpreter ({self.layout.python}): {exc}"
            ) from exc

    # -- hygiene -----------------------------------------------------------

    @staticmethod
    def _check_writable(directory: Path) -> None:
        probe = directory / ".renpy_unpack_write_test"
        try:
            probe.write_text("x", encoding="utf-8")
        except OSError as exc:
            raise InjectError(
                f"cannot write into {directory} ({exc}).\n"
                "  --inject works by adding a script to the game directory, which "
                "means it needs write access there -- unusual for an installed game "
                "(Program Files is read-only by default).\n"
                "  Use --runtime instead: it reads the archives through the game's "
                "own runtime without writing anything into the game."
            ) from exc
        finally:
            try:
                probe.unlink()
            except OSError:
                pass

    def _cleanup(self, script: Path, scratch: Path) -> list[Path]:
        """Remove what we added, reporting anything we could not.

        ``.rpyc`` matters as much as the ``.rpy``: leaving the compiled form behind
        means the game would re-run the extraction on every launch.
        """
        leftovers: list[Path] = []
        targets = [script, script.with_suffix(".rpyc")]
        if self.keep_script:
            targets = targets[1:]  # keep the source, still drop the compiled form

        for target in targets:
            try:
                target.unlink(missing_ok=True)
            except OSError:
                leftovers.append(target)
            if target.exists():
                leftovers.append(target)

        try:
            shutil.rmtree(scratch, ignore_errors=True)
        except OSError:  # pragma: no cover - defensive
            pass
        return leftovers

    @staticmethod
    def _log_tail(log: str, lines: int = 12) -> str:
        if not log:
            return "  (the script wrote no log at all)"
        tail = [line for line in log.splitlines() if line.strip()][-lines:]
        return "  --- inject.log tail ---\n" + "\n".join("  " + line for line in tail)


def discover_for_inject(game_root: Path, python: Path | None = None) -> RuntimeLayout:
    """Find the interpreter and launcher, or explain what is missing."""
    try:
        return discover_runtime(game_root, python=python)
    except RuntimeUnavailable as exc:
        raise InjectError(str(exc)) from exc
